name: ESPHome Build

on:
  push:
    branches: ["main"]
    tags: ["v*.*.*"]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build ESPHome firmware
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Extract ESPHome version from firmware.yaml
      id: esphome_version
      run: |
        # Extract min_version from firmware.yaml
        VERSION=$(grep -oP 'min_version:\s*\K[0-9]+\.[0-9]+\.[0-9]+' firmware/firmware.yaml)
        echo "Found ESPHome version: $VERSION"
        echo "version=$VERSION" >> $GITHUB_OUTPUT
        
    - name: Cache ESPHome
      uses: actions/cache@v3
      with:
        path: ~/.esphome
        key: ${{ runner.os }}-esphome-${{ steps.esphome_version.outputs.version }}-${{ hashFiles('firmware/firmware.yaml') }}
        restore-keys: |
          ${{ runner.os }}-esphome-${{ steps.esphome_version.outputs.version }}-
          
    - name: Build ESPHome firmware
      run: |
        echo "Building with ESPHome version: ${{ steps.esphome_version.outputs.version }}"
        docker run --rm \
          -v "${PWD}":/config \
          -v ~/.esphome:/config/.esphome \
          esphome/esphome:${{ steps.esphome_version.outputs.version }} \
          compile /config/firmware/firmware.yaml
    
    - name: Get version tag
      id: version
      run: |
        if [[ $GITHUB_REF == refs/tags/* ]]; then
          echo "tag=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
          echo "version=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
        else
          echo "tag=main-$(date +%Y%m%d-%H%M%S)" >> $GITHUB_OUTPUT
          echo "version=main-$(date +%Y%m%d-%H%M%S)" >> $GITHUB_OUTPUT
        fi
    
    - name: Rename firmware files
      run: |
        # Only rename the actual firmware binary, not test files or dependencies
        # Use 2>/dev/null to suppress permission denied errors from inaccessible directories
        firmware_bin=$(find firmware/.esphome/build/ -type f -name "*.bin" -path "*/firmware.ino.bin" 2>/dev/null | head -1)
        if [ -f "$firmware_bin" ]; then
          firmware_dir=$(dirname "$firmware_bin")
          mv "$firmware_bin" "$firmware_dir/firmware-${{ steps.version.outputs.version }}.bin"
          echo "Renamed firmware binary to: firmware-${{ steps.version.outputs.version }}.bin"
        else
          echo "Warning: No firmware.ino.bin found, looking for main firmware binary..."
          # Fallback: look for firmware binary in .pioenvs subdirectory, exclude CMake artifacts and dependencies
          firmware_bin=$(find firmware/.esphome/build/ -type f -name "*.bin" \
            -path "*/.pioenvs/*/firmware.bin" \
            2>/dev/null | head -1)
          
          if [ -f "$firmware_bin" ]; then
            firmware_dir=$(dirname "$firmware_bin")
            mv "$firmware_bin" "$firmware_dir/firmware-${{ steps.version.outputs.version }}.bin"
            echo "Renamed firmware binary to: firmware-${{ steps.version.outputs.version }}.bin"
          else
            echo "Warning: No firmware.bin found in .pioenvs, trying broader search..."
            # Last resort: look for any .bin but exclude known build artifacts and dependencies
            firmware_bin=$(find firmware/.esphome/build/ -type f -name "*.bin" \
              -not -path "*/CMakeFiles/*" \
              -not -path "*/.piolibdeps/*" \
              -not -path "*/managed_components/*" \
              -not -path "*/test*" \
              -not -name "*ABI*" \
              -not -name "*Determine*" \
              2>/dev/null | head -1)
            
            if [ -f "$firmware_bin" ]; then
              firmware_dir=$(dirname "$firmware_bin")
              basename=$(basename "$firmware_bin" .bin)
              mv "$firmware_bin" "$firmware_dir/${basename}-${{ steps.version.outputs.version }}.bin"
              echo "Renamed firmware binary: ${basename}-${{ steps.version.outputs.version }}.bin"
            else
              echo "Error: No suitable firmware binary found!"
              echo "Available .bin files:"
              find firmware/.esphome/build/ -type f -name "*.bin" 2>/dev/null | head -10 || echo "None found or permission denied"
              exit 1
            fi
          fi
        fi
        
    - name: Upload firmware artifacts
      uses: actions/upload-artifact@v4
      with:
        name: firmware-${{ steps.version.outputs.version }}
        path: |
          **/*-${{ steps.version.outputs.version }}.bin
          
    - name: Create Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/v')
      with:
        files: |
          **/*-${{ steps.version.outputs.version }}.bin