name: ESPHome Build

on:
  push:
    branches: ["main"]
    tags: ["v*.*.*"]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build ESPHome firmware
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Extract ESPHome version from firmware.yaml
      id: esphome_version
      run: |
        # Extract min_version from firmware.yaml
        VERSION=$(grep -oP 'min_version:\s*\K[0-9]+\.[0-9]+\.[0-9]+' firmware/firmware.yaml)
        echo "Found ESPHome version: $VERSION"
        echo "version=$VERSION" >> $GITHUB_OUTPUT
        
    - name: Cache ESPHome
      uses: actions/cache@v3
      with:
        path: ~/.esphome
        key: ${{ runner.os }}-esphome-${{ steps.esphome_version.outputs.version }}-${{ hashFiles('firmware/firmware.yaml') }}
        restore-keys: |
          ${{ runner.os }}-esphome-${{ steps.esphome_version.outputs.version }}-
          
    - name: Build ESPHome firmware
      run: |
        echo "Building with ESPHome version: ${{ steps.esphome_version.outputs.version }}"
        docker run --rm \
          -v "${PWD}":/config \
          -v ~/.esphome:/config/.esphome \
          esphome/esphome:${{ steps.esphome_version.outputs.version }} \
          compile /config/firmware/firmware.yaml
    
    - name: Get version tag
      id: version
      run: |
        if [[ $GITHUB_REF == refs/tags/* ]]; then
          echo "tag=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
          echo "version=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
        else
          echo "tag=main-$(date +%Y%m%d-%H%M%S)" >> $GITHUB_OUTPUT
          echo "version=main-$(date +%Y%m%d-%H%M%S)" >> $GITHUB_OUTPUT
        fi
    
    - name: Rename firmware files
      run: |
        find . -name "*.bin" -type f | while read file; do
          dir=$(dirname "$file")
          basename=$(basename "$file" .bin)
          mv "$file" "$dir/${basename}-${{ steps.version.outputs.version }}.bin"
        done
        
    - name: Upload firmware artifacts
      uses: actions/upload-artifact@v4
      with:
        name: firmware-${{ steps.version.outputs.version }}
        path: |
          **/*-${{ steps.version.outputs.version }}.bin
          
    - name: Create Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/v')
      with:
        files: |
          **/*-${{ steps.version.outputs.version }}.bin