name: ESPHome Build

on:
  push:
    branches: ["main"]
    tags: ["v*.*.*"]

permissions:
  contents: write  # Needed to create releases and push tags
  actions: read    # Needed to upload artifacts

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build ESPHome firmware
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Extract ESPHome version from firmware.yaml
      id: esphome_version
      run: |
        # Extract min_version from firmware.yaml
        VERSION=$(grep -oP 'min_version:\s*\K[0-9]+\.[0-9]+\.[0-9]+' firmware/firmware.yaml)
        echo "Found ESPHome version: $VERSION"
        echo "version=$VERSION" >> $GITHUB_OUTPUT
        
    - name: Cache ESPHome
      uses: actions/cache@v3
      with:
        path: ~/.esphome
        key: ${{ runner.os }}-esphome-${{ steps.esphome_version.outputs.version }}-${{ hashFiles('firmware/firmware.yaml') }}
        restore-keys: |
          ${{ runner.os }}-esphome-${{ steps.esphome_version.outputs.version }}-
          
    - name: Build ESPHome firmware
      run: |
        echo "Building with ESPHome version: ${{ steps.esphome_version.outputs.version }}"
        docker run --rm \
          -v "${PWD}":/config \
          -v ~/.esphome:/config/.esphome \
          esphome/esphome:${{ steps.esphome_version.outputs.version }} \
          compile /config/firmware/firmware.yaml
    
    - name: Get version tag
      id: version
      run: |
        if [[ $GITHUB_REF == refs/tags/* ]]; then
          echo "tag=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
          echo "version=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
        else
          echo "tag=main-$(date +%Y%m%d-%H%M%S)" >> $GITHUB_OUTPUT
          echo "version=main-$(date +%Y%m%d-%H%M%S)" >> $GITHUB_OUTPUT
        fi
    
    - name: Copy firmware files with version
      run: |
        # Copy firmware binaries with versioned names to avoid permission issues
        # Create a working directory for output files
        mkdir -p firmware_output
        
        echo "Looking for compiled firmware binary..."
        firmware_found=false
        
        # First attempt: Look for firmware.ino.bin (ESPHome Arduino builds)
        firmware_bin=$(find firmware/.esphome/build/ -type f -name "*.bin" -path "*/firmware.ino.bin" 2>/dev/null | head -1)
        if [ -f "$firmware_bin" ]; then
          cp "$firmware_bin" "firmware_output/firmware-${{ steps.version.outputs.version }}.bin"
          echo "✅ Copied firmware.ino.bin to: firmware-${{ steps.version.outputs.version }}.bin"
          firmware_found=true
        else
          echo "No firmware.ino.bin found, looking for main firmware binary..."
          
          # Second attempt: Look for firmware.bin in .pioenvs subdirectory
          firmware_bin=$(find firmware/.esphome/build/ -type f -name "*.bin" \
            -path "*/.pioenvs/*/firmware.bin" \
            2>/dev/null | head -1)
          
          if [ -f "$firmware_bin" ]; then
            cp "$firmware_bin" "firmware_output/firmware-${{ steps.version.outputs.version }}.bin"
            echo "✅ Copied PlatformIO firmware.bin to: firmware-${{ steps.version.outputs.version }}.bin"
            firmware_found=true
          else
            echo "No PlatformIO firmware.bin found, trying broader search..."
            
            # Final attempt: Look for any suitable .bin file, exclude build artifacts
            firmware_bin=$(find firmware/.esphome/build/ -type f -name "*.bin" \
              -not -path "*/CMakeFiles/*" \
              -not -path "*/.piolibdeps/*" \
              -not -path "*/managed_components/*" \
              -not -path "*/test*" \
              -not -name "*ABI*" \
              -not -name "*Determine*" \
              2>/dev/null | head -1)
            
            if [ -f "$firmware_bin" ]; then
              basename=$(basename "$firmware_bin" .bin)
              cp "$firmware_bin" "firmware_output/${basename}-${{ steps.version.outputs.version }}.bin"
              echo "✅ Copied firmware binary to: ${basename}-${{ steps.version.outputs.version }}.bin"
              firmware_found=true
            fi
          fi
        fi
        
        if [ "$firmware_found" = false ]; then
          echo "❌ Error: No suitable firmware binary found!"
          echo "Available .bin files:"
          find firmware/.esphome/build/ -type f -name "*.bin" 2>/dev/null | head -10 || echo "None found or permission denied"
          echo "Build directory structure:"
          ls -la firmware/.esphome/build/ 2>/dev/null || echo "Build directory not accessible"
          exit 1
        fi
        
        # List created files for verification
        echo "Created firmware files:"
        ls -la firmware_output/
        
    - name: Upload firmware artifacts
      uses: actions/upload-artifact@v4
      with:
        name: firmware-${{ steps.version.outputs.version }}
        path: |
          firmware_output/*-${{ steps.version.outputs.version }}.bin
          
    - name: Create Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/v')
      with:
        files: |
          firmware_output/*-${{ steps.version.outputs.version }}.bin